### ISSUE TITLE
Some small improvement

### ISSUE THREAD

**Issue by Magicianred** [fojanb/weather-app#1]
Hi, nice work! Well done :)

Some small improvement:
- disable Enter button or handle it (I use it and I think that the app doesn't work... no error no result... I have thought that my city doesn't not exists in api)
- I have an error when I insert a not exists city (TypeError: Cannot read property 'temp' of undefined). Improve the null error (maybe you can retrieve direct the weather from data
```javascript
setWeather({ weather: data && data.weather ? data.weather : null });
```
then improve the null error, handle a message 'no city found' or something like that :)
- My internet connection is quite fast, but it always better add a loader to notify the user to wait :)

for the rest really compliments

**Comment by fojanb** [comment]
Thank you so much! Yes, I knew these issues and I am still working on my codes:)  I have added API forecasting as well, so I am busy a lot with it these days.

**Comment by fojanb** [comment]
Hi Simone! Thank you so much for guiding me. I added the env variable to my Foodie Friday app as well. May I ask you to check it, please? I want to make sure I have learnt all aspect of it :)

Cheers
