### ISSUE TITLE
Permission to use your repo for practice

### ISSUE THREAD

**Issue by Magicianred** [fojanb/weather-app#2]
I'd like to use your repository to practice the code. I ask you for your permission and what do you think also because there is no license declared in the repository. :)

(I'll fork the repository, so you will remain the author)

This is the organization I am using for practice
https://github.com/code-practice-organization

Thanks anyway :)

**Comment by fojanb** [comment]
Hello !
Sure you can use it. I am still working on it btw. 
Good Luck

**Comment by fojanb** [comment]
oh btw! please use your own API key  not mine :)

**Comment by Magicianred** [comment]
It's not a good practice put the key or secret in the code, use the env variables and don't publish your key or secret :)

https://www.rockyourcode.com/secret-keys-in-react/

https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by fojanb** [comment]
Could you please guide me how to use env var?



--------------------------------------------

Fojan Babaali, MASc, B.Eng

Web Developer

BC, Canada

**Comment by fojanb** [comment]
yes you are right but I did not know how to use env var. If there is any link about it please share it here:) thanks  lot
